"""student-school-onchange-actions

Revision ID: 27105e8f6042
Revises: 
Create Date: 2023-03-14 00:25:59.519827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27105e8f6042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_school_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'schools', ['school'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_school_fkey', 'students', 'schools', ['school'], ['name'])
    # ### end Alembic commands ###
