"""create all tables

Revision ID: ceebe45da2ae
Revises: 
Create Date: 2023-05-13 20:50:38.651101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceebe45da2ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('schools',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('gender_school', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('milestones',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_nbr', sa.Integer(), nullable=False),
    sa.Column('cohort_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_name'], ['cohorts.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_nbr', 'cohort_name')
    )
    op.create_table('students',
    sa.Column('personal_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pseudonym', sa.String(), nullable=False),
    sa.Column('github_link', sa.String(), nullable=True),
    sa.Column('cohort', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('cardano_wallet', sa.String(), nullable=True),
    sa.Column('atala_prism_did', sa.String(), nullable=True),
    sa.Column('milestones_achieved', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('pschool_token', sa.String(), nullable=True),
    sa.Column('pAcceptance_token', sa.String(), nullable=True),
    sa.Column('grant_received', sa.Numeric(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_grant', sa.Numeric(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['cohort'], ['cohorts.name'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school'], ['schools.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('personal_id'),
    sa.UniqueConstraint('atala_prism_did'),
    sa.UniqueConstraint('cardano_wallet'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_link'),
    sa.UniqueConstraint('pAcceptance_token'),
    sa.UniqueConstraint('pschool_token'),
    sa.UniqueConstraint('pseudonym')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('milestones')
    op.drop_table('schools')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
